---
title: "Data Generation : Botox case study (continuous endpoint)" 
author: "Tristan Fauvel, Quinten Health"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: cerulean
    toc: yes
    toc_float:
      collapsed: true
vignette: >
  %\VignetteIndexEntry{Data Generation : Botox case study}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteDepends{RBExT, ggplot2}
---


```{r setup, warning=F, message=F, include=FALSE}
root <- dirname(dirname(getwd()))
knitr::opts_knit$set(root.dir = root, warning = FALSE, message = FALSE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(RBExT)
library(ggplot2)
```
 
```{r}
set.seed(42)

case_study_config <- yaml::yaml.load_file(system.file("conf/case_studies/botox.yml", package = "RBExT"))
format_case_study_config(case_study_config)
```

### Generation of aggregate data

```{r}
source_data <- SourceData$new(case_study_config)

drift <- 0.4
target_sample_size_per_arm <- 100

target_data <- TargetDataFactory$new()
target_data <- target_data$create(source_data = source_data, case_study_config = case_study_config, target_sample_size_per_arm = target_sample_size_per_arm, treatment_drift = drift, summary_measure_likelihood = source_data$summary_measure_likelihood)
```

```{r}
n_replicates <- 10000
data <- target_data$generate(n_replicates = n_replicates)
print(data[1:10,])
```
```{r}
target_data$plot_sample(data)
```
### Implementation details

```{r}
read_function_code(sample_aggregate_normal_data)
``` 

```{r}

samples <- sample_aggregate_normal_data(
  mean = target_data$treatment_effect,
  variance = target_data$standard_deviation^2,
  n_replicates = n_replicates,
  n_samples_per_arm = target_data$sample_size_per_arm
)

target_data$plot_sample(samples)
```
