n_replicates: 1000
ndrift: 20
denominator_change_factor:
    - 1
sample_size_factors:
    #- 1
    - 2
    - 4
    #- 6
target_to_source_std_ratio_range:
    - 1
parallelization: TRUE
case_studies:
    - belimumab
    - botox
    - dapagliflozin
    - mepolizumab
    - aprepitant
    - teriflunomide
methods:
    - NPP
