n_replicates: 5000
ndrift: 30
denominator_change_factor:
    - 0.5
    - 1
    - 1.5
sample_size_factors:
    - 1
    - 2
    - 4
    - 6
target_to_source_std_ratio_range:
    - 1
    - 2
parallelization: True
case_studies:
    #- belimumab
    #- botox
    - dapagliflozin
    - mepolizumab
    - teriflunomide
methods:
    - RMP
