n_replicates: 10000
ndrift: 0
denominator_change_factor:
    - 1
sample_size_factors:
    - 4
target_to_source_std_ratio_range:
    - 1
parallelization: False
case_studies:
    - belimumab
    - botox
    - dapagliflozin
    - mepolizumab
    - aprepitant
    - teriflunomide
methods:
    - commensurate_power_prior
