critical_value: 0.975
confidence_level: 0.95
seed: 42
n_samples_design_prior: 1000
n_samples_mixture_approx: 1000 # Number of samples from the distribution for mixture approximation with RBesT
n_samples_quantiles_estimation: 10000 # Number of samples for quantiles estimation
compute_bayesian_ocs_mc:  False
compute_frequentist_ocs:  True
delete_old_results: True
